name: gin-demo
httpPort: :3000
grpcPort: :3001
grpc:
  - name: grpc1
    addr: localhost:8080
  - name: grpc2
    addr: localhost:8081
redis:
  - name: cache
    db: 0
    addr: redis://localhost:6379
mysql:
  - name: db1
    type: mysql
    addr: root:zhulinwei123@tcp(localhost:3306)/test_database
  - name: db1
    type: mysql
    addr: root:zhulinwei123@tcp(localhost:3306)/test_database
mongo:
  - name: db1
    addr: mongodb://localhost:27017
    database: test_database
  - name: db2
    addr: mongodb://localhost:27017
    database: test_database